/*!
 * bootstrap-progressbar v0.8.2 by @minddust
 * Copyright (c) 2012-2014 Stephan Groß
 *
 * http://www.minddust.com/project/bootstrap-progressbar/
 *
 * Licensed under the MIT license:
 * http://www.opensource.org/licenses/MIT
 */
!function(_){"use strict";var x=function(t,e){this.$element=_(t),this.options=_.extend({},x.defaults,e)};x.defaults={transition_delay:300,refresh_speed:50,display_text:"none",use_percentage:!0,percent_format:function(t){return t+"%"},amount_format:function(t,e,n){return t+" / "+e},update:_.noop,done:_.noop,fail:_.noop},x.prototype.transition=function(){var a,t,r=this.$element,i=r.parent(),o=this.$back_text,h=this.$front_text,d=this.options,p=parseInt(r.attr("data-transitiongoal")),f=parseInt(r.attr("aria-valuemin"))||0,c=parseInt(r.attr("aria-valuemax"))||100,u=i.hasClass("vertical"),l=(d.update&&"function"==typeof d.update?d:x.defaults).update,g=(d.done&&"function"==typeof d.done?d:x.defaults).done,e=(d.fail&&"function"==typeof d.fail?d:x.defaults).fail;isNaN(p)?e("data-transitiongoal not set"):(a=Math.round(100*(p-f)/(c-f)),"center"!==d.display_text||o||h||(this.$back_text=o=_("<span>").addClass("progressbar-back-text").prependTo(i),this.$front_text=h=_("<span>").addClass("progressbar-front-text").prependTo(r),u?(t=i.css("height"),o.css({height:t,"line-height":t}),h.css({height:t,"line-height":t}),_(window).resize(function(){t=i.css("height"),o.css({height:t,"line-height":t}),h.css({height:t,"line-height":t})})):(t=i.css("width"),h.css({width:t}),_(window).resize(function(){t=i.css("width"),h.css({width:t})}))),setTimeout(function(){var t,e,n;u?r.css("height",a+"%"):r.css("width",a+"%");var s=setInterval(function(){n=u?(e=r.height(),i.height()):(e=r.width(),i.width()),t=Math.round(100*e/n),e=Math.round(f+e/n*(c-f)),a<=t&&(t=a,e=p,g(r),clearInterval(s)),"none"!==d.display_text&&(n=d.use_percentage?d.percent_format(t):d.amount_format(e,c,f),"fill"===d.display_text?r.text(n):"center"===d.display_text&&(o.text(n),h.text(n))),r.attr("aria-valuenow",e),l(t,r)},d.refresh_speed)},d.transition_delay))};var t=_.fn.progressbar;_.fn.progressbar=function(s){return this.each(function(){var t=_(this),e=t.data("bs.progressbar"),n="object"==typeof s&&s;e||t.data("bs.progressbar",e=new x(this,n)),e.transition()})},_.fn.progressbar.Constructor=x,_.fn.progressbar.noConflict=function(){return _.fn.progressbar=t,this}}(window.jQuery);