version: "3.8"

services:
  api:
    build:
      context: ./source
      target: builder
      dockerfile: ./Dockerfile
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    restart: "no"

  # worker:
  #   image: worker
  #   build:
  #     context: ./source
  #   depends_on:
  #     - rabbitmq
  # rabbitmq:
  #   image: bitnami/rabbitmq:3.8.27
  #   ports:
  #     - 5673:5672

  #TODO Add ngrok line
